name: widgetsampule
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  flutter_slidable: ^0.6.0
  image_picker: ^0.7.4
  flutter_native_image: ^0.0.6

  flutter_facebook_login: ^3.0.0

  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.1.3
  firebase_storage: ^8.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


